import wikipedia, time

topics = [
    "Photosynthesis",
    "The Roman Empire",
    "Quantum mechanics",
    "Artificial intelligence",
    "The Great Wall of China",
    "William Shakespeare",
    "Pyramids of Giza",
    "Oceanography",
    "Theory of relativity",
    "The Industrial Revolution",
    "French cuisine",
    "The Beatles",
    "The Solar System",
    "Human anatomy",
    "The Cold War",
    "Renewable energy",
    "The Renaissance",
    "Microbiology",
    "The Amazon rainforest",
    "Cryptocurrencies",
    "Japanese tea ceremony",
    "The Olympic Games",
    "Astrophysics",
    "History of the internet",
    "The Civil Rights Movement",
    "Marine biology",
    "The American Civil War",
    "Modern art movements",
    "Volcanoes",
    "Western philosophy",
    "The Great Depression",
    "Nanotechnology",
    "Genetics and heredity",
    "The Middle Ages",
    "History of coffee",
    "Jazz music origins",
    "Space exploration timeline",
    "Cognitive psychology",
    "The Silk Road trade routes",
    "Robotics history",
    "Ancient Egyptian government",
    "Yoga benefits",
    "Earth's water cycle",
    "Blockchain technology",
    "History of wine making",
    "The Milky Way galaxy",
    "Ludwig van Beethoven",
    "Global climate change",
    "The Viking Age",
    "Social media impact",
    "Neuroscience basics",
    "The Mayan civilization",
    "Greek mythology gods",
    "Virtual reality applications",
    "The French Revolution",
    "Gothic architecture",
    "Blue whale biology",
    "Buddhism core beliefs",
    "The Spanish Armada",
    "Nuclear power pros and cons",
    "The Louvre Museum",
    "Human nutrition science",
    "Mount Everest climbing",
    "The printing press",
    "African geography",
    "Quantum computing",
    "The Vietnam War",
    "Organic chemistry",
    "History of baseball",
    "Biotechnology ethics",
    "Samurai culture",
    "Evolution by natural selection",
    "World Wide Web history",
    "Impressionist painters",
    "The Sahara Desert ecosystem",
    "Data science methodology",
    "The Magna Carta",
    "Geology of earthquakes",
    "Italian pasta types",
    "Elvis Presley life",
    "The Declaration of Independence",
    "Aerodynamics in aviation",
    "The Great Migration",
    "Chess strategy",
    "The Apollo 11 Moon landing",
    "Macroeconomics principles",
    "The Han Dynasty",
    "Immunology basics",
    "FIFA World Cup history",
    "The Berlin Wall fall",
    "Laws of thermodynamics",
    "The Harlem Renaissance",
    "Machu Picchu history",
    "Artificial neural networks",
    "The Age of Enlightenment",
    "Ornithology study of birds",
    "History of chocolate",
    "The European Union",
    "String theory explained",
    "The Golden Age of Piracy",
    "Tsunami causes",
    "Black Plague history",
    "Python programming language",
    "Sustainable fashion",
    "The Titanic sinking",
    "Interior design trends",
    "Climate change effects",
    "The stock market basics",
    "Yoga for beginners",
    "History of soccer",
    "Microblading",
    "How batteries work",
    "The Dead Sea",
    "SEO best practices",
    "Ancient Greece government",
    "Disneyland history",
    "How do birds fly",
    "Keto diet recipes",
    "Architectural styles",
    "The Nile River",
    "Cybersecurity threats",
    "Sleep science",
    "Illegal wildlife trade",
    "Graphic design software",
    "Meditation benefits",
    "jeans",
    "Electric cars",
    "CPR steps",
    "The internet speed",
    "Sustainable agriculture",
    "Famous serial killers",
    "World War 2",
    "How to play poker",
    "Urban legends",
    "rock",
    "Mars exploration",
    "Healthy meal prep",
    "The Great Barrier Reef",
    "Makeup artistry",
    "Endangered species list",
    "The Industrial Revolution timeline",
    "Photography basics",
    "The meaning of dreams",
    "Resume writing tips",
    "video games",
    "SpaceX launches",
    "Anxiety disorders",
    "Project management methods",
    "The Grand Canyon",
    "Cryptography basics",
    "tea",
    "Virtual reality headsets",
    "Seven Wonders of the World",
    "Learning Japanese",
    "Home automation systems",
    "The Holocaust facts",
    "Video editing software",
    "Coca-Cola",
    "Public speaking fear",
    "The Battle of Hastings",
    "Mindfulness meditation",
    "Solar panel efficiency",
    "Ice hockey rules",
    "Genealogy ancestry",
    "pizza",
    "AI pros and cons",
    "Knitting basics",
    "The Amazon river",
    "Digital marketing strategies",
    "Global warming solutions",
    "hip hop",
    "Collecting stamps",
    "The Parthenon",
    "Brazil culture",
    "Franchise business model",
    "Computer hardware components",
    "Tennis scoring rules",
    "Minimalist lifestyle",
    "Statue of Liberty",
    "Psychology",
    "martial arts",
    "soap",
    "Time management skills",
    "The ISS station",
    "Alzheimer's disease",
    "Origami paper folding",
    "libraries",
    "Investment strategies",
    "Ocean pollution causes",
    "Wedding planning checklist",
    "The periodic table",
    "Veganism diet",
    "anime",
    "Podcast production",
    "currency",
    "Ethical hacking",
    "Landscape design ideas"
]


#print(wikipedia.page("New York").content)
index = 0
failed = 0

for i in topics:

    index+=1
    print(index, "/", len(topics), ",", failed, "failed")

    try:

        text = (wikipedia.summary(i))
        #print(text)

        with open("texts/wikipedia/"+i+".txt", "w") as file:
            file.write(text)

        time.sleep(1)

    except:
        print(f"Failed: {i}")
        failed += 1